export const WIDGET_VIEWER_LAYOUTS = 'WIDGET_VIEWER_LAYOUTS';
export const WIDGET_VIEWER_ITEMS = 'WIDGET_VIEWER_ITEMS';
export const WIDGET_VIEWER_RESIZE_HANDLES = 'WIDGET_VIEWER_RESIZE_HANDLES';
export const WIDGET_VIEWER_NAME = 'WIDGET_VIEWER_NAME';
export const WIDGET_VIEWER_LAYOUTS_ON_GRID = 'WIDGET_VIEWER_LAYOUTS_ON_GRID';
export const WIDGET_VIEWER_ITEMS_ON_BREAKPOINT = 'WIDGET_VIEWER_ITEMS_ON_BREAKPOINT';
export const REMOVE_WIDGET = 'REMOVE_WIDGET';

