export const CREATE_VIEWER = 'CREATE_VIEWER';
export const CONTROLLER_VIEWER_ITEMS = 'CONTROLLER_VIEWER_ITEMS';
export const CONTROLLER_VIEWER_RESIZE_HANDLES = 'CONTROLLER_VIEWER_RESIZE_HANDLES';
export const CONTROLLER_VIEWER_NAME = 'CONTROLLER_VIEWER_NAME';

