export const APP_PERMISSION = 'APP_PERMISSION';

export const APP_MOBILE_MODE = 'APP_MOBILE_MODE';
export const APP_WINDOW_WIDTH = 'APP_WINDOW_WIDTH';
export const APP_TITLE = 'APP_TITLE';
export const APP_SUB_TITLE = 'APP_SUB_TITLE';

export const APP_USER_PROFILE = 'APP_USER_PROFILE';
export const APP_CONNECTED = 'APP_CONNECTED';
export const APP_GC_CODE = 'APP_GC_CODE';

export const APP_POP_WIDGET_MOUNTED = 'APP_POP_WIDGET_MOUNTED';

export const APP_SHOW_TITLE = 'APP_SHOW_TITLE';

export const APP_INC_CHART_MOUNTED = 'APP_INC_CHART_MOUNTED';
