export const MAP_AREA_OF_OPS = 'MAP_AREA_OF_OPS';
export const CURRENT_VIEW_NAME = 'CURRENT_VIEW_NAME';

export const CURRENT_PLAN_INFO_VIEW = 'CURRENT_PLAN_INFO_VIEW';
export const CURRENT_ALERT_INFO_VIEW = 'CURRENT_ALERT_INFO_VIEW';

// eslint-disable-next-line no-shadow
export enum CURRENT_VIEW_TYPE {
  NONE = 'NONE',
  CONTROL = 'CONTROL',

  WIDGET_WEATHER = 'WIDGET_WEATHER',
  WIDGET_TRAFFIC = 'WIDGET_TRAFFIC',

  WIDGET_DRAW = 'WIDGET_PLAN',
  WIDGET_ORBAT = 'WIDGET_ORBAT',

  WIDGET_AIR_MISSION = 'WIDGET_AIR_MISSION',
  WIDGET_AIR_POWER = 'WIDGET_AIR_POWER',
  WIDGET_AIR_DEFENCE = 'WIDGET_AIR_DEFENCE',
  WIDGET_AIR_SPACE = 'WIDGET_AIR_SPACE',
  WIDGET_SURVEILLANCE = 'WIDGET_SURVEILLANCE',

  WIDGET_SEA = 'WIDGET_SEA',
  WIDGET_LAND = 'WIDGET_LAND',
  WIDGET_INFO = 'WIDGET_INFO',
  WIDGET_CYBER = 'WIDGET_CYBER',

  WIDGET_CAMPAIGN = 'WIDGET_CAMPAIGN',

  WIDGET_ENEMY_TARGET = 'WIDGET_ENEMY_TARGET',
  WIDGET_ENEMY_DEFENCE = 'WIDGET_ENEMY_DEFENCE',
}
